<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="TestNGModifierGet" duration-ms="1" started-at="2017-11-26T13:39:06Z" finished-at="2017-11-26T13:39:06Z">
    <groups>
    </groups>
    <test name="MyTests" duration-ms="1" started-at="2017-11-26T13:39:06Z" finished-at="2017-11-26T13:39:06Z">
      <class name="TestNGModifierGet">
        <test-method status="FAIL" signature="getTest()[pri:0, instance:TestNGModifierGet@1e643faf]" name="getTest" duration-ms="1" started-at="2017-11-26T16:39:06Z" finished-at="2017-11-26T16:39:06Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at TestNGModifierGet.getTest(TestNGModifierGet.java:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at Actions.testngStart(Actions.java:53)
	at Actions.action(Actions.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.hpe.lr.java.replay.ScriptContainer.invoke(ScriptContainer.java:68)
	at com.hpe.lr.java.replay.ScriptContainer.action(ScriptContainer.java:59)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getTest -->
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:TestNGModifierGet@1e643faf]" name="setUpClass" is-config="true" duration-ms="0" started-at="2017-11-26T16:39:06Z" finished-at="2017-11-26T16:39:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
      </class> <!-- TestNGModifierGet -->
    </test> <!-- MyTests -->
  </suite> <!-- TestNGModifierGet -->
</testng-results>
